### ISSUE TITLE
importing SciMLSensitivity on mybinder with julia 1.8.1 kills julia

### ISSUE THREAD

**Issue by schlichtanders** [SciML/SciMLSensitivity.jl#734]
Locally everything worked, but going to mybinder I get an immediate kill if I `import SciMLSensitivity`

you can reproduce this by
- opening my binder jupyterlab instance https://mybinder.org/v2/gh/jolin-io/KI2022-tutorial-universal-differential-equations/main
- opening a terminal in there
- executing `julia --project`
- and running `import SciMLSensitivity`

![image](https://user-images.githubusercontent.com/4255480/191585963-ea78a001-b8c6-4add-b8f0-58045186cb0e.png)

SciMLSensitivty version 7.10.0

**Comment by ChrisRackauckas** [comment]
Yeah, I'm not sure what to do here. It would need to get elevated to Julialang/julia since packages don't have control over the memory usage in the loading process. In general it should be made to GC appropriately, and maybe cut back on cores if on a smaller memory machine (since the multithreading makes the concurrent memory usage increase).

But anyways, those are discussions for Base Julia since this will happen with any sufficiently large package. Let me know when you open it since I'll want to follow it.
