### ISSUE TITLE
Neural Ordinary Differential Equations with Flux produces NaNs

### ISSUE THREAD

**Issue by SirLukeSchande** [SciML/SciMLSensitivity.jl#859]
I just saw that the output of the example [Neural Ordinary Differential Equations with Flux](https://docs.sciml.ai/SciMLSensitivity/stable/examples/neural_ode/neural_ode_flux/#Neural-Ordinary-Differential-Equations-with-Flux) is a vector of NaNs.

I did not try to run it locally but it seems that it has been that way ever since the code switched from Optim to NLopt.

**Comment by ChrisRackauckas** [comment]
The BFGS just isn't needed there so I removed it. What was going on is that the initial hessian estimate of I is unstable. In Optim we can set an initial step norm to be small to prevent the instability. But in NLopt we cannot, so it's just unstable. But since it's not needed I'll just remove it from the docs and the example will do fine.
